apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-high
spec:
  hard:
    cpu: {{ .Values.cpu_limit }}
    memory: {{ .Values.memory_limit }}
    pods: {{ .Values.pod_limit }}
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values: ["high"]
