apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.name_namespace }}
  name: pod-reader
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources: {{ .Values.resources | toJson }}
  verbs: {{ .Values.verbs | toJson }}
