apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: {{ .Values.request_cpu}}
    requests.memory: {{ .Values.requests_memory}}
    limits.cpu: {{ .Values.cpu_limit}}
    limits.memory: {{ .Values.memory_limit}}
    requests.nvidia.com/gpu: {{ .Values.request_gpu}}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: {{ .Values.configmaps_quota}}
    persistentvolumeclaims: {{ .Values.persistentvolumeclaims}}
    pods: {{ .Values.pods}}
    replicationcontrollers: {{ .Values.replicationcontrollers}}
    secrets: {{ .Values.secrets}}
    services: {{ .Values.services}}
    services.loadbalancers: {{ .Values.services_loadbalancers}}